# This is a basic workflow to help you get started with Actions
name: Release

# Controls when the action will run.
on:
  workflow_dispatch

env:
  MODULE_NAME: kw-warfare

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          # Fetch all versions for tag/changelog generation
          fetch-depth: 0

      - name: Calculate Version
        id: calculate_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
          release_branches: 'main'

      - name: Update Module
        id: update_module
        env:
          NEW_VERSION: ${{ steps.calculate_version.outputs.new_version }}
          NEW_TAG: ${{ steps.calculate_version.outputs.new_tag }}
        run: |
          echo "${NEW_VERSION}"
          echo "${NEW_TAG}"
          jq '. + {"version": env.NEW_VERSION, "download": (env.GITHUB_SERVER_URL + "/" + env.GITHUB_REPOSITORY + "/releases/download/" + env.NEW_TAG + "/module.zip")}' module.json > _module.json
          mv _module.json module.json

      - name: Update Changelog
        id: update_changelog
        env:
          CHANGELOG: ${{ steps.calculate_version.outputs.changelog }}
        run: |
          mv CHANGELOG.md _CHANGELOG.md || touch _CHANGELOG.md
          echo "${CHANGELOG}" > CHANGELOG.md
          cat _CHANGELOG.md >> CHANGELOG.md
          rm -f _CHANGELOG.md

      - name: Commit Changes
        id: commit_changes
        uses: EndBug/add-and-commit@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          add: module.json CHANGELOG.md
          message: |
            chore(build): Releasing ${{ steps.calculate_version.outputs.new_tag }}

      - name: Commit Tag
        id: commit_tag
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.calculate_version.outputs.new_tag }}
          release_name: Release ${{ steps.calculate_version.outputs.new_tag }}
          body: |
            Changes in this release:
            ${{ steps.calculate_version.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Build Zip
        id: build_zip
        env:
          NEW_TAG: ${{ steps.calculate_version.outputs.new_tag }}
        run: |
          zip -r /tmp/module.zip . -x .git\*
          mv /tmp/module.zip ./module.zip

      # Create a release for this specific version
      - name: Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          prerelease: false
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './module.json, ./module.zip'
          tag: ${{ steps.calculate_version.outputs.new_tag }}
